version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu/webapp

hooks:
  BeforeInstall:
    - location: ./codedeploy/app_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./codedeploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./codedeploy/app_start.sh
      timeout: 300
      runas: root