name: CICD

env:
  ARTIFACT_NAME: csye6225-webapp-${{github.GITHUB_SHA}}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - a6

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
      - run: rm -rf node_modules/
      - name: Zip Artifact
        run: |
           pwd
           ls -al
           mkdir -p codedeploy_artifact
           zip -r ${{ env.ARTIFACT_NAME }} codedeploy/*sh appspec.yml
           pwd
           ls -al
           mv  ${{ env.ARTIFACT_NAME }} codedeploy_artifact/
           ls -al
           pwd
           cd codedeploy_artifact
           ls -al
           pwd
           cd ..
           pwd
           ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
            aws-region: ${{env.AWS_REGION}}

      - name: Upload Artifact to S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_CODE_DEPLOY_BUCKET}}

      - name: Make CodeDeploy API call
        run: |
            output = $(aws deploy create-deployment \
              --application-name ${{env.CODEDEPLOY_APPLICATION_NAME }} \
              --region ${{env.AWS_REGION}} \
              --output json)

              echo $output

              dId = $(echo $ouput | jq -r '.deploymentId')

              aws deploy wait deployment-successful --deployment-id $dId
