name: pull request check workflow
on:
  pull_request:
    branches:
      - master
      - a2
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: sudo npm install
      - run: sudo npm run build --if-present
      - run: sudo npm test
        env:
          CI: true

